package com.civic.controller;
import com.civic.dto.*; import com.civic.entity.*; import com.civic.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/admin") @RequiredArgsConstructor @PreAuthorize("hasRole('SUPER_ADMIN')") public class SuperAdminController {private final UserRepository users;private final DepartmentRepository departments;private final PetitionRepository petitions;private final PollRepository polls;private final SignatureRepository signatures;private final VoteRepository votes;private final PetitionReviewRepository reviews;
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){return Map.of("citizens",users.findByRoleOrderByIdDesc(Role.CITIZEN).size(),"officials",users.findByRoleOrderByIdDesc(Role.OFFICIAL).size(),"pendingOfficials",users.findByRoleAndVerifiedFalseOrderByIdDesc(Role.OFFICIAL).size(),"departments",departments.findAll().size(),"petitions",petitions.count(),"polls",polls.count(),"signatures",signatures.count(),"votes",votes.count(),"reviews",reviews.count());}
 @GetMapping("/citizens") public List<UserResponse> citizens(){return users.findByRoleOrderByIdDesc(Role.CITIZEN).stream().map(this::map).toList();}
 @GetMapping("/officials") public List<UserResponse> officials(){return users.findByRoleOrderByIdDesc(Role.OFFICIAL).stream().map(this::map).toList();}
 @GetMapping("/officials/pending") public List<UserResponse> pending(){return users.findByRoleAndVerifiedFalseOrderByIdDesc(Role.OFFICIAL).stream().map(this::map).toList();}
 @PutMapping("/officials/{id}") public UserResponse manage(@PathVariable Long id,@RequestBody OfficialAdminRequest r){User u=users.findById(id).orElseThrow(()->new RuntimeException("Official not found"));if(u.getRole()!=Role.OFFICIAL)throw new RuntimeException("User is not an official");u.setVerified(r.isApproved());u.setActive(r.isActive());u.setDepartment(r.getDepartment());u.setDesignation(r.getDesignation());return map(users.save(u));}
 @PutMapping("/citizens/{id}") public UserResponse manageCitizen(@PathVariable Long id,@RequestBody Map<String,Object> r){User u=users.findById(id).orElseThrow(()->new RuntimeException("Citizen not found"));if(u.getRole()!=Role.CITIZEN)throw new RuntimeException("User is not a citizen");u.setActive(Boolean.TRUE.equals(r.get("active")));return map(users.save(u));}
 @DeleteMapping("/officials/{id}") public void reject(@PathVariable Long id){User u=users.findById(id).orElseThrow(()->new RuntimeException("Official not found"));u.setVerified(false);u.setActive(false);users.save(u);}
 @GetMapping("/departments") public List<Department> deps(){return departments.findAll();}
 @GetMapping("/petitions") public List<PetitionResponse> allPetitions(){return petitions.findAll().stream().map(p->PetitionResponse.builder().id(p.getId()).title(p.getTitle()).description(p.getDescription()).category(p.getCategory()).location(p.getLocation()).department(p.getDepartment()).goal(p.getGoal()).currentSignatures(p.getCurrentSignatures()).status(p.getStatus()).creatorName(p.getCreator().getName()).creatorEmail(p.getCreator().getEmail()).rejectionReason(p.getRejectionReason()).proposedSolution(p.getProposedSolution()).actionPlan(p.getActionPlan()).progressPercent(p.getProgressPercent()).createdAt(p.getCreatedAt()).updatedAt(p.getUpdatedAt()).build()).toList();}
 @GetMapping("/polls") public List<PollResponse> allPolls(){return polls.findAll().stream().map(p->PollResponse.builder().id(p.getId()).title(p.getTitle()).description(p.getDescription()).options(p.getOptions()).targetLocation(p.getTargetLocation()).department(p.getDepartment()).status(p.getStatus()).createdById(p.getCreatedBy().getId()).createdByName(p.getCreatedBy().getName()).closeDate(p.getCloseDate()).totalVotes(votes.countByPoll(p)).createdAt(p.getCreatedAt()).updatedAt(p.getUpdatedAt()).build()).toList();}
 private UserResponse map(User u){return new UserResponse(u.getId(),u.getName(),u.getEmail(),u.getRole(),u.getLocation(),u.getDepartment(),u.getDesignation(),u.isVerified(),u.isActive(),u.getCreatedAt());}
}
